context:
  version: 0.4.1

package:
  name: openapi-llm
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/openapi-llm/openapi_llm-${{ version }}.tar.gz
    sha256: b64966cca783146f1722517f96067f16e09a0b0e84715bebda3a512883188e6e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - aiohttp
    - jsonref
    - pyyaml
    - requests

tests:
  - python:
      imports:
        - openapi_llm
      pip_check: true

about:
  homepage: https://github.com/vblagoje/openapi-llm
  summary: Convert and invoke OpenAPI specifications as LLM tool/function definitions
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/vblagoje/openapi-llm

extra:
  recipe-maintainers:
    - moritzwilksch
