context:
  version: "0.4.2"

package:
  name: openapi-llm
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/openapi-llm/openapi_llm-${{ version }}.tar.gz
    sha256: 68e33c59aaa0c4b99d4e1156be2f72b7c4dbe4a21180e3cf4294cb23c2dbcb51

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - aiohttp
    - jsonref
    - pyyaml
    - requests

tests:
  - python:
      imports:
        - openapi_llm
      pip_check: true

about:
  homepage: https://github.com/vblagoje/openapi-llm
  summary: Convert and invoke OpenAPI specifications as LLM tool/function definitions
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/vblagoje/openapi-llm

extra:
  recipe-maintainers:
    - moritzwilksch
